version: '3.8'

services:
  web:
    container_name: web_container
    build:
      context: ./
      dockerfile: Dockerfile
    command: sh -c "gunicorn ColibriAssetAccounting.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    expose:
      - 8000
    links:
      - redis
  nginx:
    container_name: nginx_container
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
  redis:
    container_name: redis_container
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  static_volume:
  media_volume:
  redis_data: