version: '3.3'

services:
  db:
    container_name: postgres_container
    image: db:0.3.0
    build:
      context: ./postgres
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    restart: always

  web:
    container_name: web_container
    image: web:0.3.0
    build:
      context: ./
      dockerfile: Dockerfile
    command: sh -c "python manage.py migrate && gunicorn ColibriAssetAccounting.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
      - /home/dgolov:/home/app/logs
    expose:
      - 8000
    depends_on:
      - db
    links:
      - redis
      - db
    restart: always

  nginx:
    container_name: nginx_container
    image: nginx:0.3.0
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    restart: always

  redis:
    container_name: redis_container
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  static_volume:
  media_volume:
  redis_data: