# Generated by Django 4.1.7 on 2023-12-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_customuser_city_customuser_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='location',
        ),
        migrations.AddField(
            model_name='customuser',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='users', to='web.location', verbose_name='Местоположение'),
        ),
    ]
