# Generated by Django 4.1.7 on 2023-05-22 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_location_address_alter_location_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='location',
        ),
        migrations.RemoveField(
            model_name='history',
            name='price',
        ),
        migrations.RemoveField(
            model_name='history',
            name='state',
        ),
        migrations.RemoveField(
            model_name='history',
            name='status',
        ),
        migrations.AddField(
            model_name='history',
            name='event_name',
            field=models.TextField(default=1, verbose_name='Наименование события'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='new_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_history', to='web.location', verbose_name='Местоположение'),
        ),
        migrations.AddField(
            model_name='history',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='history',
            name='new_state',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='history',
            name='new_status',
            field=models.CharField(blank=True, choices=[('in_work', 'В работе'), ('broken', 'Сломано'), ('under_repair', 'В ремонте'), ('in_reserve', 'В запасе')], max_length=256, null=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='history',
            name='old_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_history', to='web.location', verbose_name='Местоположение'),
        ),
        migrations.AddField(
            model_name='history',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='history',
            name='old_state',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='history',
            name='old_status',
            field=models.CharField(blank=True, choices=[('in_work', 'В работе'), ('broken', 'Сломано'), ('under_repair', 'В ремонте'), ('in_reserve', 'В запасе')], max_length=256, null=True, verbose_name='Статус'),
        ),
    ]
