# Generated by Django 4.1.7 on 2023-05-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_assetimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetimage',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='assetimage',
            name='image',
            field=models.ImageField(upload_to='images/assets/', verbose_name='Изображенеие'),
        ),
    ]
