# Generated by Django 4.1.7 on 2023-05-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_assetimage_title_alter_assetimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='new_name',
            field=models.CharField(blank=True, choices=[('in_work', 'В работе'), ('broken', 'Сломано'), ('under_repair', 'В ремонте'), ('in_reserve', 'В запасе')], max_length=256, null=True, verbose_name='Новое название'),
        ),
        migrations.AddField(
            model_name='history',
            name='old_name',
            field=models.CharField(blank=True, choices=[('in_work', 'В работе'), ('broken', 'Сломано'), ('under_repair', 'В ремонте'), ('in_reserve', 'В запасе')], max_length=256, null=True, verbose_name='Старое название'),
        ),
        migrations.AlterField(
            model_name='history',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи'),
        ),
        migrations.AlterField(
            model_name='history',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Новая стоимость'),
        ),
        migrations.AlterField(
            model_name='history',
            name='new_state',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Новое состояние'),
        ),
        migrations.AlterField(
            model_name='history',
            name='new_status',
            field=models.CharField(blank=True, choices=[('in_work', 'В работе'), ('broken', 'Сломано'), ('under_repair', 'В ремонте'), ('in_reserve', 'В запасе')], max_length=256, null=True, verbose_name='Новый статус'),
        ),
        migrations.AlterField(
            model_name='history',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Старая стоимость'),
        ),
        migrations.AlterField(
            model_name='history',
            name='old_state',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Старое состояние'),
        ),
        migrations.AlterField(
            model_name='history',
            name='old_status',
            field=models.CharField(blank=True, choices=[('in_work', 'В работе'), ('broken', 'Сломано'), ('under_repair', 'В ремонте'), ('in_reserve', 'В запасе')], max_length=256, null=True, verbose_name='Старый татус'),
        ),
    ]
