# Generated by Django 4.1.7 on 2023-06-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_asset_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('level', models.CharField(choices=[('success', 'Успешно'), ('error', 'Ошибка'), ('warning', 'Предупреждение'), ('info', 'Информация'), ('debug', 'Отладка')], max_length=256, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время сообщения')),
            ],
        ),
    ]
