# Generated by Django 4.1.7 on 2023-06-12 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0014_alter_notifications_options_notifications_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='file',
        ),
        migrations.AddField(
            model_name='order',
            name='file_path',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Путь к файлу отчета'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
