# Generated by Django 4.1.7 on 2023-08-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_remove_order_file_order_file_path_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='ozon_slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Ссылка на ozon'),
        ),
    ]
