# Generated by Django 4.1.7 on 2023-09-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_asset_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
            preserve_default=False,
        ),
    ]
