# Generated by Django 4.1.7 on 2023-10-22 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_alter_asset_ozon_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='web.asset', verbose_name='Родительский актив'),
        ),
    ]
