# Generated by Django 4.1.7 on 2023-10-22 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_asset_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_list', to='web.asset', verbose_name='Родительский актив'),
        ),
    ]
